# name: Linters & Checkers

# on:
#   push:
#     branches:
#       - main
#   pull_request: {}

# concurrency:
#   group: ${{ github.workflow }}-${{ github.ref }}
#   cancel-in-progress: true

# jobs:
#   checks:
#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v3

#     - uses: actions/setup-python@v4
#       with:
#         python-version: '3.10'

#     - name: Install requirements
#       run: pip install black flake8 isort

#     - name: black
#       run: black . --check --diff
#     - name: flake8
#       run: |
#         flake8 factfinder
#         flake8 tests
#     - name: isort
#       run: |
#         isort factfinder --check --diff
#         isort tests --check --diff
